kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: php
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: php-deployment
    spec:
      containers:
        - name: php
          image: hyperion.azurecr.io/my-php-app
          ports:
            - name: "http-port"
              containerPort: 80
      imagePullSecrets:
        - name: regcred
